# version: "3"
services:
  mysql:
    image: mysql:8
    container_name: mysql-hst
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: 12345
#    volumes:
#      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - app_network
  nginx:
    image: nginx:latest
    container_name: nginx-hst
    ports:
      - "8083:80"
    restart: always
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html/homes_staging
    depends_on:
      - php
    networks:
      - app_network
  php:
#    image: php:8.2-fpm
    build:
      context: ./
      dockerfile: ./php/Dockerfile
    tty: true
    working_dir: /var/www/html/homes_staging
    container_name: php-hst
    environment:
      PHP_IDE_CONFIG: serverName=homesstaging.ru
    volumes:
      - ./:/var/www/html/homes_staging
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

#  php:
#    image: php:8.2-fpm
#    container_name: php-hst
#    working_dir: /var/www/html/homes_staging
#    volumes:
#      - .:/var/www/html/homes_staging
#    environment:
#     PHP_IDE_CONFIG: serverName=homesstaging
#    networks:
#      - app_network

#  app:
#    build:
#      context: ./
#    tty: true
#    working_dir: /app
#    container_name: php-hs
#    volumes:
#      - ./:/app
#    networks:
#      - app_network